name: Deploy to Vercel

on:
  push:
    branches:
      - main # Change this to your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9" # Change this to the Python version you need

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel_branch: main # Change this if needed
